name: al_khabeer
description: al_khabeer App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android

  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: any
  internet_connection_checker: ^1.0.0+1
  http: any
  #  responsive_sizer: ^3.1.1
  shared_preferences:
  slide_action:
  bloc:
  lottie: any
  flutter_svg: any
  cached_network_image: any
  flutter_screenutil: ^5.8.4
  #  animated_snack_bar: ^0.3.0
  pinput: ^2.2.31
  #  flutter_rating_bar: ^4.0.1
  #  shimmer: ^2.0.0
#  firebase_messaging: any
  flutter_local_notifications: ^14.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: any
  #  flutter_osm_plugin: any
  url_launcher: any
  #  latlong2: any
  #  flutter_map: any
  logger: ^1.1.0
  dropdown_button2: ^1.9.2
  flutter_switch: ^0.3.2
  bottom_navy_bar: ^6.0.0
  #  flutter_keyboard_visibility: ^5.4.0
  carousel_slider: any
  intl_phone_number_input: ^0.7.2
  #  expandable: ^5.0.1
  awesome_dialog: ^3.0.2
  group_button: ^5.2.2
  #  buttons_tabbar: ^1.3.6
  #  im_stepper: ^1.0.1+1
#  firebase_core: any
  #  syncfusion_flutter_datepicker: ^21.1.37
  table_calendar: ^3.0.9
  intl: ^0.18.0
  persistent_bottom_nav_bar: ^5.0.2
  #  firebase_dynamic_links: any
  #  photo_view: ^0.14.0
  collection:


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#f1f1f1"
  adaptive_icon_foreground: "assets/icons/logo_forground.png"

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lotties/
    - assets/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: cairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: cairoSemiBold
      fonts:
        - asset: assets/fonts/cairo_semi_bold.ttf
